version: '3.8'

services:
  mongodb:
    build:
      context: ./mongodb
    container_name: cf_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    container_name: cf_server
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/clusterflow
      - JWT_SECRET=supersecretclusterflowkey
      - PORT=8080
    depends_on:
      - mongodb

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile.scheduler
    container_name: cf_scheduler
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/clusterflow
      - JWT_SECRET=supersecretclusterflowkey
      - PORT=8081
    depends_on:
      - mongodb
      - server

  agent:
    build:
      context: ./backend
      dockerfile: Dockerfile.agent
    environment:
      - SERVER_URL=http://server:8080/api/v1
      - ADMIN_EMAIL=admin@clusterflow.io
      - ADMIN_PASSWORD=adminpassword
    depends_on:
      - server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cf_frontend
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongodb_data:
